name: Test coverage

on: workflow_dispatch

jobs:
  cover:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          8.0.x
          9.0.x

    - name: Install reportgenerator
      run: dotnet tool install -g dotnet-reportgenerator-globaltool

    - name: Test coverage
      run: dotnet test test/W4k.AspNetCore.Correlator.UnitTests --nologo /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput="../../TestResults/"

    - name: Generate report (lcov)
      run: reportgenerator -reports:TestResults/coverage.*.info -targetdir:"TestResults/lcov" -reporttypes:lcov

    - name: Generate report (lcov)
      run: reportgenerator -reports:TestResults/coverage.*.info -targetdir:"TestResults/html" -reporttypes:html

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: w4k-aspnetcore-correlator-test-results-${{ github.sha }}
        path: TestResults
