name: Test coverage

on: workflow_dispatch

jobs:
  cover:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x
          9.0.x
          10.0.x

    - name: Install reportgenerator
      run: dotnet tool install -g dotnet-reportgenerator-globaltool

    - name: Test coverage
      run: dotnet test --project test/W4k.AspNetCore.Correlator.UnitTests --configuration Release --coverage --coverage-output-format cobertura --results-directory ./TestResults

    - name: Generate report (lcov)
      run: reportgenerator -reports:"TestResults/*.cobertura.xml" -targetdir:"TestResults/lcov" -reporttypes:lcov

    - name: Generate report (html)
      run: reportgenerator -reports:"TestResults/*.cobertura.xml" -targetdir:"TestResults/html" -reporttypes:html

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: w4k-aspnetcore-correlator-test-results-${{ github.sha }}
        path: TestResults
