name: Test coverage

on: workflow_dispatch

jobs:
  cover:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
      
    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Install reportgenerator
      run: dotnet tool install -g dotnet-reportgenerator-globaltool

    - name: Test coverage
      run: dotnet test --nologo -f netcoreapp3.1 /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput="./TestResults/"
      working-directory: test/W4k.AspNetCore.Correlator.UnitTests

    - name: Generate report
      run: reportgenerator -reports:TestResults/coverage.cobertura.xml -targetdir:"./TestResults/html" -reporttypes:HTML
      working-directory: test/W4k.AspNetCore.Correlator.UnitTests

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: w4k-aspnetcore-correlator-test-results-${{ github.sha }}
        path: test/W4k.AspNetCore.Correlator.UnitTests/TestResults
